// export const CREATE_ORDER = 'CREATE_ORDER';
export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_STATUS_SUCCESS = 'LOAD_STATUS_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const DELETE_ORDER_OPTIMISTIC = 'DELETE_ORDER_OPTIMISTIC';
